version: '3'

services:

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    # image: nginx:1.17.3
    ports: 
      - 5000:80
      - 443:443
  
  apipython:
    build: ./api
    container_name: apipython
    restart: always
    environment: 
      - APP_NAME=production
    expose: 
      - 5000